# label rules used by .github/workflows/label.yml

api:
  - magpie/api/**/*

cli:
  - magpie/cli/**/*

# label 'ci' all automation-related steps and files
ci:
  - .*  # all '.<>' files
  - .github/**/*
  - ci/**/*
  - hooks/**/*
  - Makefile
  - Dockerfile*
  - setup.cfg

doc:
  - "*.rst"
  - "*.example"
  - doc/**/*
  - requirements-doc.txt

db:
  - magpie/db.py
  - magpie/models.py

plugin:
  - magpie/adapter/**/*

security:
  - magpie/security.py

tests:
  - tests/**/*
  - requirements-dev.txt

ui:
  - magpie/ui/**/*
