# configuration to setup readthedocs
python:
  version: 3.7
  install:
    - requirements: requirements-docs.txt
      method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
