# configuration to setup readthedocs
version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 3.7
  install:
    - requirements: requirements-docs.txt
    # required for OpenAPI generation
    - requirements: requirements.txt
#    - method: pip
#      path: .
#      extra_requirements:
#        - docs
  system_packages: true
