language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
cache:
  - pip
  - directories:
      - $HOME/conda
      - $HOME/downloads
# includes PR when base branch = master
if: branch = master OR tag IS present
env:
  global:
    - CONDA_HOME=$HOME/conda
    - DOWNLOAD_CACHE=$HOME/downloads
  matrix:
    - TEST_TARGET=test-local    START_TARGET=
    - TEST_TARGET=test-remote   START_TARGET=start
    - TEST_TARGET=coverage      START_TARGET=
addons:
  postgresql: "9.6"
postgres:
  adapter: postgresql
  database: magpie
  username: postgres
  password: qwerty
before_install:
  - python -V
  - uname -a
  - lsb_release -a
  - export PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - export CONDA_ENV=magpie-${TRAVIS_PYTHON_VERSION}
  - export CONDA_PREFIX=$HOME/conda/envs/magpie-${TRAVIS_PYTHON_VERSION}
  - export PATH=${CONDA_HOME}/bin:$PATH
  - hash -r
  - env
  - make conda-base
  - make sysinstall
  - echo $CONDA_PREFIX
  - echo $CONDA_ENV
  #==== magpie env and constants ===
  - mkdir -p ./env
  - cp -f ./ci/magpie.env ./env/magpie.env
install:
  # TODO: remove when fixed and merged (see requirements.txt and Makefile)
  - ${CONDA_PREFIX}/bin/pip install gunicorn paste
  - |
    if [ "${TRAVIS_PYTHON_VERSION}" -eq "2.7" ]; then
      ${CONDA_PREFIX}/bin/pip install --upgrade --force-reinstall python-openid && \
      ${CONDA_PREFIX}/bin/pip uninstall -y python3-openid;
    else
      ${CONDA_PREFIX}/bin/pip install --upgrade --force-reinstall python3-openid && \
      ${CONDA_PREFIX}/bin/pip uninstall -y python-openid;
    fi
  - make install install-dev
  - make version
before_script:
  - psql -c 'create database magpie;' -U postgres
  - echo $CONDA_PREFIX
  - echo $CONDA_ENV
  - export PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - export CONDA_ENV=magpie-${TRAVIS_PYTHON_VERSION}
  - export CONDA_PREFIX=$HOME/conda/envs/magpie-${TRAVIS_PYTHON_VERSION}
  - export PATH=${CONDA_HOME}/bin:$PATH
  - hash -r
  - env
  - echo $CONDA_PREFIX
  - echo $CONDA_ENV
script:
  - make $START_TARGET $TEST_TARGET
notifications:
  email: false
jobs:
  include:
    - stage: deploy
      script: echo "Deploying..."
      deploy:
        provider: script
        script: make conda-env docker-push
        skip_existing: true
        on:
          tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
