language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
cache:
  - pip
  - directories:
      - $HOME/conda
      - $HOME/downloads
# includes PR when base branch = master
if: branch = master OR tag IS present
env:
  global:
    - CONDA_HOME=$HOME/conda
    - DOWNLOAD_CACHE=$HOME/downloads
  matrix:
    - APP_NAME=magpie-$TRAVIS_PYTHON_VERSION TARGET=test-local
    - APP_NAME=magpie-$TRAVIS_PYTHON_VERSION TARGET=test-remote
    - APP_NAME=magpie-$TRAVIS_PYTHON_VERSION TARGET=coverage
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - hash -r
  - make sysinstall
install:
  - make install install-dev
  - make version
script:
  - make $TARGET
notifications:
  email: false
jobs:
  include:
    - stage: deploy
      script: echo "Deploying..."
      deploy:
        provider: script
        script: make conda-env docker-push
        skip_existing: true
        on:
          tags: true
