language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
cache:
  - pip
  - directories:
      - $HOME/conda
      - $HOME/downloads
# includes PR when base branch = master
if: branch = master OR tag IS present
env:
  global:
    - CONDA_HOME=$HOME/conda
    - DOWNLOAD_CACHE=$HOME/downloads
  matrix:
    - TARGET=test-local
    - TARGET=test-remote
    - TARGET=coverage
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - export CONDA_ENV=magpie-${TRAVIS_PYTHON_VERSION}
  - export PATH="${CONDA_HOME}/bin":$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - env
  - make conda-base
  - make sysinstall
  - echo $CONDA_PREFIX
  - echo $CONDA_ENV
  - conda env list
  - conda init bash
install:
  - make install install-dev
  - make version
script:
  - make $TARGET
notifications:
  email: false
jobs:
  include:
    - stage: deploy
      script: echo "Deploying..."
      deploy:
        provider: script
        script: make conda-env docker-push
        skip_existing: true
        on:
          tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
