language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
cache:
  - pip
  - directories:
      - $HOME/conda
      - $HOME/downloads
# includes PR when base branch = master
if: branch = master OR tag IS present
env:
  global:
    - CONDA_HOME=$HOME/conda
    - DOWNLOAD_CACHE=$HOME/downloads
  matrix:
    - TEST_TARGET=test-local    START_TARGET=
    - TEST_TARGET=test-remote   START_TARGET=start
    - TEST_TARGET=coverage      START_TARGET=
addons:
  postgresql: "9.6"
postgres:
  adapter: postgresql
  database: magpie
  username: postgres
  password: qwerty
before_script:
  - psql -c 'create database magpie;' -U postgres
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - export PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - export CONDA_ENV=magpie-${TRAVIS_PYTHON_VERSION}
  - export CONDA_PREFIX=$HOME/conda/envs/magpie-${TRAVIS_PYTHON_VERSION}
  - export PATH=${CONDA_HOME}/bin:$PATH
  - hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  #- conda info -a
  - env
  - make conda-base
  - make sysinstall
  - echo $CONDA_PREFIX
  - echo $CONDA_ENV
  - pip install gunicorn
  #- conda env list
  #- conda init bash
  #==== magpie env and constants ===
  - mkdir -p ./env
  - cp -f ./ci/magpie.env ./env/magpie.env
install:
  - make install install-dev
  - make version
script:
  - make $START_TARGET $TEST_TARGET
notifications:
  email: false
jobs:
  include:
    - stage: deploy
      script: echo "Deploying..."
      deploy:
        provider: script
        script: make conda-env docker-push
        skip_existing: true
        on:
          tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
