# look for secrets pushed by mistake

name: Secret Scan
on:
  - pull_request
  - push

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
    #- uses: max/secret-scan@master
    #  with:
    #    repo-token: "${{ secrets.GITHUB_TOKEN }}"
