# look for secrets pushed by mistake

name: Labeler
on:
  - pull_request
  - push

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: max/secret-scan@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
