# look for secrets pushed by mistake

name: Secret Scan
on:
  - pull_request
  - push

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
    #- uses: max/secret-scan@master
    #  with:
    #    repo-token: "${{ secrets.GITHUB_TOKEN }}"

  # ref: https://github.com/svdarren/secrets-workflow/blob/9633bc1195a1ca1d4d70415aa4eff6cf55d706de/.github/workflows/secrets.yml
  gitleak:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: docker pull zricethezav/gitleaks
      #- run: |
      #    docker run --name=gitleaks --volume $GITHUB_WORKSPACE:/workspace/ \
      #    -v --exclude-forks --redact --threads=1 --branch=$GITHUB_REF --repo-path=/workspace/
      #- run: docker run --rm --name=gitleaks -v /tmp/:/code/ zricethezav/gitleaks -v --repo-path=/code/gitleaks
      # @todo command is failing
      #- run: gitleaks -v --exclude-forks --redact --threads=1 --branch=$GITHUB_REF --repo-path=$GITHUB_WORKSPACE

      - uses: eshork/gitleaks-action@v1.0.0
      - uses: CySeq/gitcret@v2
