# run test suites

name: Tests
on:
  - pull_request
  - push

# Reference:
#   https://github.com/actions/setup-python
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    env:
      # override make command to install directly in active python
      CONDA_COMMAND: ""
    services:
      # Label used to access the service container
      postgres:
        image: postgres  # DockerHub
        env:
          POSTGRES_USER: magpie
          POSTGRES_PASSWORD: qwerty
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        # python-version: ["2.7", "3.5", "3.6", "3.7", "3.8"]
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8"]
        allow-failure: [false]
        test-case: [test-local]
        include:
          # linter tests
          - os: ubuntu-latest
            python-version: 3.7
            allow-failure: false
            test-case: check
          # remote test
          - os: ubuntu-latest
            python-version: 3.7
            allow-failure: true
            test-case: start test-remote
          # test allowed failing because of old versions
          - os: ubuntu-latest
            python-version: 2.7
            allow-failure: true
            test-case: test-local
          - os: ubuntu-latest
            python-version: 3.5
            allow-failure: true
            test-case: test-local
          # coverage test
          - os: ubuntu-latest
            python-version: 3.7
            allow-failure: false
            test-case: coverage
          # smoke test of Docker image
          - os: ubuntu-latest
            python-version: 3.5
            allow-failure: true
            test-case: test-docker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Intall Dependencies
        run: make install-pkg install-dev version
      - name: Display Packages
        run: pip freeze
      - name: Setup Environment Variables
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ./ci/magpie.env
      - name: Display Environment Variables
        run: |
          hash -r
          env | sort
      - name: Run Tests
        run: make stop ${{ matrix.test-case }}
      - name: Upload coverage report
        if: ${{ success() }}
        run: |
          if [ -f "./reports/coverage.xml" ]; then
            bash <(curl -s https://codecov.io/bash)
            python-codacy-coverage -r reports/coverage.xml)
          else
            echo "Codecov did not collect coverage reports"
          fi
